### PR TITLE
cleanup <description> @ detail

### PR DESCRIPTION
**Pull request by xerc**

### CODE REVIEW

**Comment by aimeos** [comment]
Why is this change necessary? Can you please explain a little bit more in detail?

**Comment by xerc** [comment]
1. missing @ og:
2. HTML @ RTE

**Comment by aimeos** [comment]
OK, for og:title it's missing.

I'm unsure if the html_entity_decode() is really necessary because
```html
<p><strong>Meta descriptions &amp; keywords are important because they are shown in the search engine result page</strong></p>
```
is added as 
```
Meta descriptions &amp; keywords are important because they are shown in the search engine result page
```
which should be correct according to: https://stackoverflow.com/questions/20585754/does-need-to-be-amp-in-the-meta-description

**Comment by xerc** [comment]
Bildschirmfoto 2021-03-05 um 19 34 26

**Comment by xerc** [comment]
Bildschirmfoto 2021-03-05 um 19 35 46

**Comment by aimeos** [comment]
`&nbsp` isn't double encoded and is valid in meta tags.

**Comment by aimeos** [comment]
`strip_tags()` has been added to the template: https://github.com/aimeos/ai-client-html/commit/a974deaa74c6f70069f088f37237420620e525de

**Pull request closed without merging**
