### PR TITLE
Hide "Catalog List Type" selector and "Sort"

### PR DESCRIPTION
**Pull request by Metalicss**
This will make "Catalog List Type" selector and "Sort" text hidden if the selected category has no product assigned.

### CODE REVIEW

**Comment by aimeos** [comment]
Thanks a lot for your improvement! :-)

Could you please adapt the tests so we can merge it without problems? Simply move
https://github.com/aimeos/ai-client-html/blob/master/client/html/tests/Client/Html/Catalog/Lists/StandardTest.php#L92
to 
https://github.com/aimeos/ai-client-html/blob/master/client/html/tests/Client/Html/Catalog/Lists/StandardTest.php#L117

**Comment by Metalicss** [comment]
I did. (I hope i did, as a new Github user)

**Comment by aimeos** [comment]
Not yet. You have to push your local changes (git push)

**Comment by gilbertsoft** [comment]
On Windows and Mac you can use the [GitHub Desktop App](https://desktop.github.com/), cool tool for beginners. There you can sync your local repo with the online repo by clicking on Sync (some times push) on the top right after you commited your changes. But the tool is very limited to standard tasks and most errors you have to solve by the command line git.

Other tool if you like to have a Windows Explorer integration is [TortoiseGit](https://tortoisegit.org/). But keep in mind this can slow down your system!

**Comment by aimeos** [comment]
@Metalicss You can do small changes also in the GibHub web interface. That's the easiest way.

**Pull request merged**
