### PR TITLE
[FIX] Outlook Conditional @ emails

### PR DESCRIPTION
**Pull request by xerc**

### CODE REVIEW

**Comment by aimeos** [comment]
This code is automatically generated by MJML. Is this the output of a newer version of MJML?

**Comment by xerc** [comment]
manuell FIX of the OL syntax

**Comment by aimeos** [comment]
Then, your changes will be overwritten the next time the HTML is generated from the MJML files which will revert your PR. If this is a bugfix, please create a PR in the repository of the MJML project.

**Comment by xerc** [comment]
if the other users do not fresh-generate these files this is BROKEN

**Comment by aimeos** [comment]
Sure, but if you don't get the fix into the MJML project, it won't stay for long in the Aimeos templates if they are regenerated by the MJML parser.

**Comment by xerc** [comment]
if you did not look it up & if you do not update your source since two years - someone other has to fix it
https://github.com/mjmlio/mjml/blob/bc90c8e05d59911cc6824fce23d5a8311d5c8d5f/packages/mjml-core/src/helpers/skeleton.js#L33

**Comment by aimeos** [comment]
If it's fixed in MJML too, then it's fine.

**Pull request merged**
