### PR TITLE
Preselect option for attributes

### PR DESCRIPTION
**Pull request by gilbertsoft**
Merged from my version 2017.01, was not able to test with master source. @since in the docu section has to be updated...

### CODE REVIEW

**Comment by aimeos** [comment]
Thanks again! :-)
Please use "@since 2017.04" for the new configuration option

**Comment by gilbertsoft** [comment]
I wrote the wrong version before, I merged this from the lastest version of 2016. I updated the system to 2017.01 and now I got this message on the detail page:

Class "\Aimeos\Client\Html\Catalog\Detail\Image\Standard" not available

I deactivated my own extensions for this test, so the default code should be executed.

But now I was able to test my changes in this pr and it seems everything runs as expected!

**Comment by gilbertsoft** [comment]
Found it: seems the setting client/html/catalog/detail/standard/subparts has changed and my settings are not longer valid!

**Comment by aimeos** [comment]
The template system has radically simplified in 2017.01. You can see a full list of backward incompatible changes in the changelog: https://aimeos.org/docs/Developers/Changelog

**Pull request merged**
