### PR TITLE
force absolute URL @ og:image

### PR DESCRIPTION
**Pull request by xerc**

### CODE REVIEW

**Comment by aimeos** [comment]
The `asset()` method isn't part of Aimeos (it's Laravel) and thus can't be used in Aimeos templates that must work with Symfony and TYPO3 too.

**Comment by xerc** [comment]
than PLEASE implement this the correct way

**Comment by aimeos** [comment]
The absolute URL for images depends on your APP_URL setting in your .env file which is then used for the image base URL here:
https://github.com/aimeos/aimeos-laravel/blob/master/src/default.php#L50

**Comment by xerc** [comment]
absolute URL is required for share-images also if APP_URL=/

**Comment by aimeos** [comment]
That doesn't work if `APP_URL=/` and the e-mails won't contain working URLs too with this setting.

**Pull request closed without merging**
