### PR TITLE
[FIX] W3C <input>

### PR DESCRIPTION
**Pull request by xerc**
Attribute maxlength is only allowed when the input type is email, password, search, tel, text, or url.

### CODE REVIEW

**Comment by aimeos** [comment]
Do you have any official reference for that? The whatwg docs doesn't state such a restriction:
https://html.spec.whatwg.org/multipage/input.html#attr-input-maxlength

**Comment by xerc** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

**Comment by xerc** [comment]
OR https://html.spec.whatwg.org/multipage/input.html#concept-input-apply

**Comment by aimeos** [comment]
Thanks. There are more number input fields with `maxlength` in the templates. Can you please change them too?
https://github.com/aimeos/ai-client-html/search?q=maxlength

**Comment by aimeos** [comment]
Are you able to change the other occurences too?

**Pull request closed without merging**
